### ISSUE TITLE
bs-config file does not work

### ISSUE THREAD

**Issue by electricBonfire** [johnpapa/lite-server#41]
I am using the `npm` package for `lite-server`. I have tried both `bs-config.json` and `bs-config.js` neither seemed to be loaded when running `npm run lite`.

I found this post:
http://stackoverflow.com/questions/35149408/cant-change-the-base-folder-for-lite-server-in-angular-2-application

They mention this not working for the package installed by `npm`, which is my experience

**Comment by set321go** [comment]
which version of lite-server are you using? Until I updated the version used in the angular example app it would not find bs-config.json file.

**Comment by johnpapa** [comment]
the config file was introduced in v2

**Comment by electricBonfire** [comment]
Thanks, I was using: `"lite-server": "^1.3.1",` taken from the angular2 quickstart guide

**Comment by bond4u** [comment]
Have similar problem with lite-server 2.2.0.
I do get output 
"[1] Did not detect a `bs-config.json` or `bs-config.js` override file. Using lit
e-server defaults..."
even though I do have bs-config.js file present in current folder.
I think it's caused because I have an error in bs-config.js file.
The check "if (err.code && err.code === 'MODULE_NOT_FOUND')" seems too vague...
