### ISSUE TITLE
About the 'Why' of lite-server

### ISSUE THREAD

**Issue by bastienJS** [johnpapa/lite-server#59]
Hello John,

I have browser-sync already running before I saw your lite-server on the angular 2 hero sample.

You say: "When creating a SPA there are routes that are only known to the browser. For example, /customer/21 may be a client side route for an Angular app. If this route is entered manually or linked to directly as the entry point of the Angular app (aka a deep link) the static server will receive the request, because Angular is not loaded yet. The server will not find a match for the route and thus return a 404."

But is this not the job of the e.g. asp.net backend to handle the 404 from the pushstate route and return the index.html?

It seems to me from your description that you do the same as this guy:

http://www.eriklieben.com/enabling-pushstate-in-asp-net-vnext/

Is this correct that you do the same because then I do not try the lite-server?!

**Comment by cgmartin** [comment]
You can use whatever webserver you'd like that has route fallback or rewrite capability. Lite server is meant as a no-hassle development server for the angular 2 quickstart. We want users to focus on the angular code, rather than having to mess around and configure various servers. For production use, we leave the choice of server up to you.

I am not familar with ASP.Net Vnext, but if it works for you, great! Use it instead.
